site_name: Sqlify
site_description: A simple sql builder based on standard Python type hints
site_url: https://sqlify.massadas.com/
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
  language: en
repo_name: G4brym/sqlify
repo_url: https://github.com/G4brym/sqlify
edit_uri: ''
plugins:
  - search
  - markdownextradata:
      data: data
nav:
  - Sqlify: index.md
  - getting-started.md
  - basic-queries.md
  - Migrations:
      - migrations/basic-usage.md
      - migrations/typer-cli.md
  - Advanced Queries:
      - advanced-queries/fields.md
      - advanced-queries/group.md
      - advanced-queries/having.md
      - advanced-queries/order.md
      - advanced-queries/auxiliary-queries.md
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/G4brym/sqlify
